version: '2'
services:
  db:
    image: forestguardian/postgres_postgis
    environment:
      POSTGRES_USER: forestguardian
      POSTGRES_PASSWORD: rVgJcwDvs5A7aMZG
    ports:
      - '5432:5432'
    volumes:
      - vol-postgres:/var/lib/postgresql/data
    networks:
      intranet:
        ipv4_address: 172.16.238.10
  redis:
    image: library/redis:3.0.7
    ports:
          - '6379:6379'
    networks:
          intranet:
            ipv4_address: 172.16.238.11
  sidekiq:
    image: forestguardian/backend
    env_file:
      - '.env.web'
    environment:
      RAILS_ENV: production
    command: bundle exec sidekiq -C /ForestGuardianBackend/config/sidekiq.yml
    networks:
      intranet:
        ipv4_address: 172.16.238.12
  web:
    env_file:
      - '.env.web'
    image: forestguardian/backend
    command: bash -c 'git pull; bundle exec rails s -p 80 -b "0.0.0.0"'
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      intranet:
        ipv4_address: 172.16.238.13

volumes:
  vol-postgres: {}

networks:
  intranet:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1